version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
